maxIpfixMessageLen: 100
collectors:
- remoteAddress: 35.194.97.218:2055
  localAddress: 0.0.0.0:50101
templates:
- id: 1001
  template:
  - name: SourceIPv4Address
  - name: DestinationIPv4Address
  - name: ProtocolIdentifier
  - name: OctetDeltaCount
  - name: PacketDeltaCount
- id: 1002
  template:
  - name: SourceIPv4Address
  - name: DestinationIPv4Address
  - name: ProtocolIdentifier
  - name: SourceTransportPort
  - name: DestinationTransportPort
  - name: IngressInterface
  - name: OctetDeltaCount
  - name: PacketDeltaCount
